---
title: "Course Project 2"
author: "Alex Fennell"
output: html_document
---

```{r libraries, message=FALSE}
    library(dplyr)
    library(ggplot2)
    library(lubridate)
```

## Loading the data

```{r download-data, cache=TRUE}
fileurl<-"https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
if (!file.exists("CP2data.csv.bz2")){
    download.file(fileurl,"CP2data.csv.bz2",method="curl")
}
storm<-read.csv("CP2data.csv.bz2",stringsAsFactors = FALSE)
```

Since we are interested in the public health and economic consequences of various
event types, the first thing I want to do is select rows that have some amount of
property damage, crop damage, fatalities, or injuries.
```{r processing the data}
stormfilt<-storm%>%
    filter(PROPDMG>0 | CROPDMG>0 | FATALITIES>0 |INJURIES>0)
stormfilt$BGN_DATE<-strptime(stormfilt$BGN_DATE,format="%m/%d/%Y")
stormfilt$BGN_DATE<-as.POSIXct(stormfilt$BGN_DATE)
stormfilt$Year<-format(stormfilt$BGN_DATE,"%Y")
stormfilt$EVTYPE<-as.factor(stormfilt$EVTYPE)

```
